version: '3.8'

services:
  mongo:
    image: mongo:5.0
    container_name: fiware-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - green-net  

  orion:
    image: fiware/orion-ld
    container_name: fiware-orion 
    ports:
      - "1026:1026"
    depends_on:
      - mongo
    command: -dbhost fiware-mongo -logLevel DEBUG 
    networks:
      - green-net  

# Khai báo mạng external
networks:
  green-net:
    external: true 

volumes:
  mongo_data: